### ISSUE TITLE
The last version that works (for me) is 440-local?

### ISSUE THREAD

**Issue by Swiftnesses** [NathanVaughn/powerpanel-business-docker#22]
Hi,

It appears the last working version is 440 for local? Any ideas what broke after this?

**Comment by Swiftnesses** [comment]
Log: 2023-02-17_08-44-16_ppbd_err.log

`Feb 17, 2023 8:44:16 AM com.cyberpowersystems.utility.Logger printToLog
SEVERE: writeNeedDowngradeWatchdogIntoPPBInfoProperties failed: java.lang.NullPointerException
Feb 17, 2023 8:44:16 AM com.cyberpowersystems.utility.Logger printToLog
INFO: inside ppbe Bootsrap.start()
Feb 17, 2023 8:44:16 AM com.cyberpowersystems.utility.Logger printToLog
INFO: heapMaxSize : 239075328 Bytes / 228 MB
Feb 17, 2023 8:44:16 AM com.cyberpowersystems.utility.Logger printToLog
INFO: Launch tomcat
Feb 17, 2023 8:44:16 AM com.cyberpowersystems.utility.Logger printToLog
INFO: Load module list setting
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: Load database https setting
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: before start
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: etc/config.properties (No such file or directory)
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: tomcat add local
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: /usr/local/PPB/./web/AgentWeb-0.0.1-SNAPSHOT.war
Feb 17, 2023 8:44:17 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-3052"]
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/8.5.76]
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardHost startInternal
SEVERE: Couldn't load specified error report valve class: [CustomErrorReportValve]
java.lang.ClassNotFoundException: CustomErrorReportValve
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:823)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 17, 2023 8:44:17 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Feb 17, 2023 8:44:17 AM org.apache.tomcat.util.descriptor.web.SecurityConstraint handleOmittedMethods
SEVERE: For security constraints with URL pattern [/*] the HTTP methods [POST GET] are uncovered.
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.ApplicationContext log
INFO: Marking servlet [jsp] as unavailable
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet [jsp] in web application [] threw load() exception
java.lang.ClassNotFoundException: org.apache.jasper.servlet.JspServlet
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1415)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1223)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:533)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:149)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1071)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4952)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5266)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 17, 2023 8:44:17 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.ApplicationContext log
INFO: Marking servlet [jsp] as unavailable
Feb 17, 2023 8:44:17 AM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet [jsp] in web application [/local] threw load() exception
java.lang.ClassNotFoundException: org.apache.jasper.servlet.JspServlet
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1415)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1223)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:533)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:149)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1071)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4952)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5266)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 17, 2023 8:44:17 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-3052"]
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: tomcat start
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: getServerBuilt : Feb 23 2022 17:59:11 UTC
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: getServerInfo : Apache Tomcat/8.5.76
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: getServerNumber : 8.5.76.0
Feb 17, 2023 8:44:17 AM com.cyberpowersystems.utility.Logger printToLog
INFO: Bootsrap.start(): startup finished in linux
`

**Comment by msg00235** [comment]
i have similar problem
When 481 or 486
Pod log display
-----
ppbd: unrecognized service
-----
But 440 doesn't have this problem
(Chinese to English translation from GOOGLE)

**Comment by NathanVaughn** [comment]
Sorry for the delay, it's been a busy time for me. Yes, anything newer than 440 doesn't work for the local version. I don't know why, I don't know how the software all works.

I have had success with my setup by using `both-486` and then putting `nginx` in front of it, blanking the Origin header.
Example config:

```nginx
events {}

http {
    server {
        listen 80;
        listen [::]:80;

        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;

        location / {
            proxy_pass http://{{ env "NOMAD_ADDR_powerpanel_http_port" }};
            proxy_set_header Origin '';
        }
    }
}
```
